# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'ECS多元流行聲樂系統'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

#demoWeb_menu:
#- {name: 'Interesting Facts',  url: 'demoWeb/facts'}
#- {name: 'Learning Resources', url: 'demoWeb/resources'}
#- {name: 'Sample Posts',       url: 'demoWeb/sample-posts'}
#- {name: 'Documentation',      url: 'demoWeb/documentation'}
#- {name: 'About',              url: 'demoWeb/about'}
#- {name: 'Contact',            url: 'demoWeb/contact'}

default_menu:
- {name: '首頁', url: 'index'}
- {name: '關於老師', url: 'about'}
- {name: '聯絡我們', url: 'contact'}

DreamArts_menu:
- {name: '首頁', url: 'DreamArts/index'}
- {name: '課程', url: 'DreamArts/courses'}
- {name: '學生活動', url: 'DreamArts/portfolio'}
- {name: '歌唱比賽', url: 'DreamArts/competition'}
- {name: '實例分享', url: 'DreamArts/sharing'}
- {name: '關於老師', url: 'DreamArts/about'}
- {name: '聯絡我們', url: 'DreamArts/contact'}

DreamOfStage_menu:
- {name: '首頁', url: 'DreamOfStage/index'}
- {name: '課程', url: 'DreamOfStage/courses'}
- {name: '學生活動', url: 'DreamOfStage/portfolio'}
- {name: '歌唱比賽', url: 'DreamOfStage/competition'}
- {name: '實例分享', url: 'DreamOfStage/sharing'}
- {name: '關於老師', url: 'DreamOfStage/about'}
- {name: '聯絡我們', url: 'DreamOfStage/contact'}

ECS_menu:
- {name: '首頁', url: 'ECS/index'}
- {name: '課程', url: 'ECS/courses'}
- {name: '學生活動', url: 'ECS/portfolio'}
- {name: '歌唱比賽', url: 'ECS/competition'}
- {name: '實例分享', url: 'ECS/sharing'}
- {name: '關於老師', url: 'ECS/about'}
- {name: '聯絡我們', url: 'ECS/contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'twitter', link: 'https://twitter.com'}
- {icon: 'facebook', link: 'https://www.facebook.com/jove.chengcy'}
- {icon: 'instagram', link: 'https://instagram.com/jove_cheng_ecs_vocal_tutor'}
#- {icon: 'envelope', link: 'mailto:hello@paulle.ca'}
#- {icon: 'rss-square', link: 'feed.xml'}
#- {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: '較新的文章'
  previous_page: '較舊的文章'

sharing_button_prompt: '歡迎分享！'

related_posts: '你可能也會喜歡...'

post_date_prefix: '發布於'
